### ISSUE TITLE
Merge detect_output_fields into one class

### ISSUE THREAD

**Issue by arevill2** [ruithnadsteud/yt_geotiff#36]
When loading single Sentinel-2 and Landsat scenes the  _detect_output_fields function is used in the GeoTiffHierarchy and JPEG2000Hierarchy classes respectively. Would be better for all loaded scenes (either single or multiple datasets; *jpeg or *tif) to use the _detect_output_fields in the RasterioGroupHierarchy class.

**Comment by brittonsmith** [comment]
Resolved in PR #38.
