### ISSUE TITLE
Improve handling of selection errors when at or beyond edge of dataset or image bounds

### ISSUE THREAD

**Issue by deastwoo** [ruithnadsteud/yt_geotiff#37]
Change selection process so that it provides more meaningful error/warning message if selection is attempted beyond the bounds of the image.

Currently selection beyond bounds of primary/load image is allowed while within a secondary image. This should change.

Also, we need to decide how to deal with selection of a secondary image field which is beyond that secondary image's bounds but within the load image's bounds (currently this fails).

**Comment by brittonsmith** [comment]
I think this was resolved in PR #38, but if it pops up again, we should examine further.
